package Pojo;
// Generated 25/02/2016 11:53:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Indicadores generated by hbm2java
 */
public class Indicadores  implements java.io.Serializable {


     private Integer idindicadores;
     private Objetivos objetivos;
     private String nombreIndicador;
     private String nickIndicador;
     private String nombreFormula;
     private Integer porcentaje;
     private Set varindicadoreses = new HashSet(0);

    public Indicadores() {
    }

	
    public Indicadores(Objetivos objetivos) {
        this.objetivos = objetivos;
    }
    public Indicadores(Objetivos objetivos, String nombreIndicador, String nickIndicador, String nombreFormula, Integer porcentaje, Set varindicadoreses) {
       this.objetivos = objetivos;
       this.nombreIndicador = nombreIndicador;
       this.nickIndicador = nickIndicador;
       this.nombreFormula = nombreFormula;
       this.porcentaje = porcentaje;
       this.varindicadoreses = varindicadoreses;
    }
   
    public Integer getIdindicadores() {
        return this.idindicadores;
    }
    
    public void setIdindicadores(Integer idindicadores) {
        this.idindicadores = idindicadores;
    }
    public Objetivos getObjetivos() {
        return this.objetivos;
    }
    
    public void setObjetivos(Objetivos objetivos) {
        this.objetivos = objetivos;
    }
    public String getNombreIndicador() {
        return this.nombreIndicador;
    }
    
    public void setNombreIndicador(String nombreIndicador) {
        this.nombreIndicador = nombreIndicador;
    }
    public String getNickIndicador() {
        return this.nickIndicador;
    }
    
    public void setNickIndicador(String nickIndicador) {
        this.nickIndicador = nickIndicador;
    }
    public String getNombreFormula() {
        return this.nombreFormula;
    }
    
    public void setNombreFormula(String nombreFormula) {
        this.nombreFormula = nombreFormula;
    }
    public Integer getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Integer porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set getVarindicadoreses() {
        return this.varindicadoreses;
    }
    
    public void setVarindicadoreses(Set varindicadoreses) {
        this.varindicadoreses = varindicadoreses;
    }




}


