package Pojo;
// Generated 11/08/2015 01:16:26 PM by Hibernate Tools 4.3.1



/**
 * Objetivos generated by hbm2java
 */
public class Objetivos  implements java.io.Serializable {


     private Integer idObjetivos;
     private Orbita orbita;
     private String nombreObjetivo;
     private String indicador;
     private Integer tipoObjetivo;

    public Objetivos() {
    }

	
    public Objetivos(Orbita orbita) {
        this.orbita = orbita;
    }
    public Objetivos(Orbita orbita, String nombreObjetivo, String indicador, Integer tipoObjetivo) {
       this.orbita = orbita;
       this.nombreObjetivo = nombreObjetivo;
       this.indicador = indicador;
       this.tipoObjetivo = tipoObjetivo;
    }
   
    public Integer getIdObjetivos() {
        return this.idObjetivos;
    }
    
    public void setIdObjetivos(Integer idObjetivos) {
        this.idObjetivos = idObjetivos;
    }
    public Orbita getOrbita() {
        return this.orbita;
    }
    
    public void setOrbita(Orbita orbita) {
        this.orbita = orbita;
    }
    public String getNombreObjetivo() {
        return this.nombreObjetivo;
    }
    
    public void setNombreObjetivo(String nombreObjetivo) {
        this.nombreObjetivo = nombreObjetivo;
    }
    public String getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(String indicador) {
        this.indicador = indicador;
    }
    public Integer getTipoObjetivo() {
        return this.tipoObjetivo;
    }
    
    public void setTipoObjetivo(Integer tipoObjetivo) {
        this.tipoObjetivo = tipoObjetivo;
    }




}


