package Pojo;
// Generated 25/02/2016 11:53:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Objetivos generated by hbm2java
 */
public class Objetivos  implements java.io.Serializable {


     private Integer idObjetivos;
     private Orbita orbita;
     private String nombreObjetivo;
     private String nickObjetivo;
     private String meta;
     private Set indicadoreses = new HashSet(0);

    public Objetivos() {
    }

	
    public Objetivos(Orbita orbita) {
        this.orbita = orbita;
    }
    public Objetivos(Orbita orbita, String nombreObjetivo, String nickObjetivo, String meta, Set indicadoreses) {
       this.orbita = orbita;
       this.nombreObjetivo = nombreObjetivo;
       this.nickObjetivo = nickObjetivo;
       this.meta = meta;
       this.indicadoreses = indicadoreses;
    }
   
    public Integer getIdObjetivos() {
        return this.idObjetivos;
    }
    
    public void setIdObjetivos(Integer idObjetivos) {
        this.idObjetivos = idObjetivos;
    }
    public Orbita getOrbita() {
        return this.orbita;
    }
    
    public void setOrbita(Orbita orbita) {
        this.orbita = orbita;
    }
    public String getNombreObjetivo() {
        return this.nombreObjetivo;
    }
    
    public void setNombreObjetivo(String nombreObjetivo) {
        this.nombreObjetivo = nombreObjetivo;
    }
    public String getNickObjetivo() {
        return this.nickObjetivo;
    }
    
    public void setNickObjetivo(String nickObjetivo) {
        this.nickObjetivo = nickObjetivo;
    }
    public String getMeta() {
        return this.meta;
    }
    
    public void setMeta(String meta) {
        this.meta = meta;
    }
    public Set getIndicadoreses() {
        return this.indicadoreses;
    }
    
    public void setIndicadoreses(Set indicadoreses) {
        this.indicadoreses = indicadoreses;
    }




}


