package Pojo;
// Generated 25/02/2016 11:53:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orbita generated by hbm2java
 */
public class Orbita  implements java.io.Serializable {


     private Integer idOrbita;
     private Nodo nodo;
     private String nombreDepartamento;
     private String vision;
     private String mision;
     private Integer posicion;
     private Set objetivoses = new HashSet(0);

    public Orbita() {
    }

	
    public Orbita(Nodo nodo) {
        this.nodo = nodo;
    }
    public Orbita(Nodo nodo, String nombreDepartamento, String vision, String mision, Integer posicion, Set objetivoses) {
       this.nodo = nodo;
       this.nombreDepartamento = nombreDepartamento;
       this.vision = vision;
       this.mision = mision;
       this.posicion = posicion;
       this.objetivoses = objetivoses;
    }
   
    public Integer getIdOrbita() {
        return this.idOrbita;
    }
    
    public void setIdOrbita(Integer idOrbita) {
        this.idOrbita = idOrbita;
    }
    public Nodo getNodo() {
        return this.nodo;
    }
    
    public void setNodo(Nodo nodo) {
        this.nodo = nodo;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public String getVision() {
        return this.vision;
    }
    
    public void setVision(String vision) {
        this.vision = vision;
    }
    public String getMision() {
        return this.mision;
    }
    
    public void setMision(String mision) {
        this.mision = mision;
    }
    public Integer getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(Integer posicion) {
        this.posicion = posicion;
    }
    public Set getObjetivoses() {
        return this.objetivoses;
    }
    
    public void setObjetivoses(Set objetivoses) {
        this.objetivoses = objetivoses;
    }




}


