package Pojo;
// Generated 11/08/2015 01:16:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organizacion generated by hbm2java
 */
public class Organizacion  implements java.io.Serializable {


     private Integer idOrganizacion;
     private String nombre;
     private String estadoorg;
     private Set nodos = new HashSet(0);

    public Organizacion() {
    }

    public Organizacion(String nombre, String estadoorg, Set nodos) {
       this.nombre = nombre;
       this.estadoorg = estadoorg;
       this.nodos = nodos;
    }
   
    public Integer getIdOrganizacion() {
        return this.idOrganizacion;
    }
    
    public void setIdOrganizacion(Integer idOrganizacion) {
        this.idOrganizacion = idOrganizacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEstadoorg() {
        return this.estadoorg;
    }
    
    public void setEstadoorg(String estadoorg) {
        this.estadoorg = estadoorg;
    }
    public Set getNodos() {
        return this.nodos;
    }
    
    public void setNodos(Set nodos) {
        this.nodos = nodos;
    }




}


