package Pojo;
// Generated 25/02/2016 11:53:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Cuenta cuenta;
     private Nodo nodo;
     private String apellidoMaterno;
     private String apellidoPaterno;
     private String nombreUsu;
     private Date fechaDeNacimiento;
     private byte[] foto;
     private String correoElectro;
     private String telefono;

    public Usuario() {
    }

	
    public Usuario(Cuenta cuenta, Nodo nodo) {
        this.cuenta = cuenta;
        this.nodo = nodo;
    }
    public Usuario(Cuenta cuenta, Nodo nodo, String apellidoMaterno, String apellidoPaterno, String nombreUsu, Date fechaDeNacimiento, byte[] foto, String correoElectro, String telefono) {
       this.cuenta = cuenta;
       this.nodo = nodo;
       this.apellidoMaterno = apellidoMaterno;
       this.apellidoPaterno = apellidoPaterno;
       this.nombreUsu = nombreUsu;
       this.fechaDeNacimiento = fechaDeNacimiento;
       this.foto = foto;
       this.correoElectro = correoElectro;
       this.telefono = telefono;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Nodo getNodo() {
        return this.nodo;
    }
    
    public void setNodo(Nodo nodo) {
        this.nodo = nodo;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getNombreUsu() {
        return this.nombreUsu;
    }
    
    public void setNombreUsu(String nombreUsu) {
        this.nombreUsu = nombreUsu;
    }
    public Date getFechaDeNacimiento() {
        return this.fechaDeNacimiento;
    }
    
    public void setFechaDeNacimiento(Date fechaDeNacimiento) {
        this.fechaDeNacimiento = fechaDeNacimiento;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getCorreoElectro() {
        return this.correoElectro;
    }
    
    public void setCorreoElectro(String correoElectro) {
        this.correoElectro = correoElectro;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


